post http://127.0.0.1:8080/PamaApi/api/User/login
Content-Type: application/json

{
    "username": "2",
    "password": "c4ca4238a0b923820dcc509a6f75849b"
}


###
post http://127.0.0.1:8080/PamaApi/api/Company
Content-Type: application/json

{
    "token": "8F3FAEE6-891D-46A8-8BAE-EA6DE1CD847C"
}


###
POST http://127.0.0.1:8080/PamaApi/api/F2Key/Bank
Content-Type: application/json

{
    "token": "289D8725-561A-4A09-AC29-C5FFAEFE2AD7"
}


###
GET https://api.instagram.com/v1/users/search
Content-Type: application/json

{
    "q": "zahmatkesh",
    "count": 10
}


###
GET http://api.openweathermap.org/data/2.5/weather?q=Tehran&appid=2c25788beeafabb24408586d70a75b29


