post http://127.0.0.1:8080/PamaApi/api/User/login
Content-Type: application/json

{
    "username": "sanyar",
    "password": "111111"
}

###
GET http://127.0.0.1:8080/HomeCleaningRest/api/v1/user



###
put http://127.0.0.1:8080/PamaApi/api/Parvane
Content-Type: application/json

{"cmpid":0,"id":null,"iranianasnaf":null,"reqdate":null,"peopid":0,"gunitid":0,"guname":null,"gubegindate":null,"gutoolsinfo":null,"guensheabat":null,"gubimemakan":0,"gubimeshobe":null,"gukargahno":0,"guzirbana":0,"gutabaghat":0,"gurent":0,"gudaraeicode":0,"guvahedmaliati":null,"guparvandemaliat":0,"gustatus":0,"gutel":null,"gufax":null,"guesteghrarplace":null,"gusigntitle":null,"gunote":null,"kind":1,"parvandekind":1,"ecoid":null,"bank":3,"hesabno":"۴۴","hesabkind":1,"hisic":151915,"isic":0,"hoghoghikind":1,"hoghoghiname":"۵۵","hoghoghishenasemeli":"۶۶","hoghoghisabtno":null,"hoghoghisabtdate":null,"parvanekind":1,"datesodor":null,"datetahvil":null,"etebarlen":0,"eparvaneno":0,"note":null,"shenasesenfi":0,"accept":0,"acceptdate":null,"bankname":"بانک تجارت","isicname":"منجمد و خشک و بسته بندی  و سورتینگ میوه جات","token":"76B5B773-0F71-4510-B455-39B153776A18"
}



###
POST http://127.0.0.1:8080/PamaApi/api/F2Key/Bank
Content-Type: application/json

{
    "token": "76B5B773-0F71-4510-B455-39B153776A18"
}


###
GET https://api.instagram.com/v1/users/search
Content-Type: application/json

{
    "q": "zahmatkesh",
    "count": 10
}


###
GET http://api.openweathermap.org/data/2.5/weather?q=Tehran&appid=2c25788beeafabb24408586d70a75b29


